[tool.poetry]
name = "glissando-synth"
version = "0.1.3"
description = ""
authors = ["Rodrigo García <yo@rodrigogarcia.me>"]

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.2.2"
numpy = "^1.19.0"
scipy = "^1.5.0"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
